retirement_api/templates/claiming.html
* Strike “age” from “By age 85…”
* Strike “the” from the second bullet of early benefit claiming age
* Make “Step 1: Explore how your claiming age affects your Social
Security retirement benefits” fit across only the first 2/3 of the page columns
=> Further content tweaks (for the design)

retirement_api/static/css/claiming.css, retirement_api/static/js/claiming-social-security.js, retirement_api/templates/claiming.html
Adds cf-notification code. __Please note:__ Warning messages are not yet pretty. 
__Also!__ Changes rounding for percentages to `Math.round` instead of `Math.floor`. :boom: :octopus:
=> cf-notification code added

retirement_api/static/css/claiming.css, retirement_api/static/js/claiming-social-security.js, retirement_api/templates/claiming.html
Moves lifestyle questions and buttons to the top of their container. Images will slide up as content slides down. Heights of containers are now automatic rather than fixed.
=> New iteration on lifestyle questions

retirement_api/migrations/0001_initial.py
Currently in the repository we're not following the best practice of using migrations.  We'd need to call `syncdb` in order to create the initial tables.  If the table schemas ever change we will need to drop the tables and all its data.  While this is unlikely with this team, our best practice is to always include a migration.  As of Django 1.9 (whenever we get there) migrations will be required, so this is future proofing too.  
@higs4281 Can you please approve?
=> Adding a migration for the models

retirement_api/urls.py
*This* is why /retirement/static/ was working in the first place.
=> Removed static URL route

retirement_api/static/retirement/js/claiming-social-security.js
Change the graph height breakpoints in the JavaScript to match the page breakpoints in the CSS
- Small graph height now starts at `$(window).width() < 850`
- Medium graph height and large graph height are currently the same, but the medium breakpoint is now `$(window).width() >= 850 && $(window).width() < 1045`
- This should be checked at all screen sizes
=> Change breakpoints for graph height

retirement_api/static/retirement/js/claiming-social-security.js
Lifestyle buttons for each question stay active when answering another question.
- Changed the scope of which lifestyle buttons are deactivated when another button is clicked
=> Fix lifestyle buttons to stay highlighted

retirement_api/static/retirement/css/claiming.css, retirement_api/templates/claiming.html
* Fix the line break in the H1 for different device sizes
* Change text around "By 85" and remove tooltip
=> Small content styling fixes

retirement_api/static/retirement/js/claiming-social-security.js
Prevents tooltips from falling off the left side of small screens and lines up tooltip pointers with their triggers when the tooltips are near the edges of the viewport.
- Added a check to adjust tooltips positioned off the left edge of the viewport
- Modified the check to adjust tooltips positioned off the right edge of the viewport to line the pointers up with their triggers
- I tested this in Safari, Chrome, Chrome's device emulator, and my iPhone 6. Could use more testing on any other devices we have handy.
- @mistergone: Do the changes I made to your tooltip JS look OK?
Tooltips near the left edge of the viewport should look like so:
And ones near the right edge should look like so:
=> Tooltip fixes

retirement_api/static/retirement/js/claiming-social-security.js
Adjust auto-scrolling to the graph and next steps for a smoother experience
- Changed the `isElementInView()` offset from +150px to -150px
- Stopped auto-scrolling to the graph if the API returns an error
- Added 20px of padding to the scrolled-to element
- I've tested this in Chrome, Safari, Chrome's device emulator and my iPhone 6. Testing in any other browsers or devices is greatly appreciated (I'm looking at you, IE).
- @mistergone: Did I move the `isElementInView()` check in the right place for the graph?
=> Adjust auto-scroll

CHANGELOG.md, README.md, browser_testing/features/navigation.feature, browser_testing/features/steps/steps_navigation.py, retirement_api/urls.py
This implements the new url reflecting the new app title
- two urls
- old urls
- Readme reference to standalone app's url
- browser tests updated
- Browser tests have been updated but will fail until this is deployed, because tests run against the live site.
- @mistergone @marteki @niqjohnson 
- we still have a number of class and other references to 'claiming-social-security,' which i see no need to mess with.
- this needs to be paired with a change to server redirects for the old url
=> update url to reflect new title

retirement_api/static/retirement/js/claiming-social-security.js
Change the graph's auto-scroll point to accommodate the new graph layout
- Set the graph's auto-scroll point to the graph header instead of the monthly/annual income toggle
- Tested and working on Chrome, Safari, Chrome's device emulator and my iPhone 6.
=> Change graph's auto-scroll target

retirement_api/static/retirement/js/claiming-social-security.js
Stop the slider from jumping back to full retirement age when the window is resized (especially in mobile browsers where a `resize` event is fired when the browser hides its chrome as the page is scrolled).
- Change `drawIndicator()` to remember user-selected age after they've gotten their estimate
- I've tested this in Chrome, Safari, Chrome's device emulator, and my iPhone 6. Seems to be working as expected.
- @mistergone: Does that new conditional look OK?
=> Prevent slider from resetting on window resize

retirement_api/fixtures/retiredata.json, retirement_api/templates/claiming.html
Adds tooltips in the "working in your 60s" question to explain effect of claiming early and working
- adds new tooltip in database
- adds references to the tooltip in the 'sixties' question's answers
- adds a tooltip content div to the main template
- to test, be sure to pull in new content with `python manage.py loaddata retiredata.json`
- @marteki @niqjohnson 
- update content on build after PR is merged and deployed
=> add tooltip content to sixties question per issue #117

retirement_api/static/retirement/js/claiming-social-security.js
Short description explaining the high-level reason for the pull request
- add conditional to handle consumers who are 70 years old
- if testing in UnityBox, be sure to run `python manage.py collectstatic` before checking
- @niqjohnson @marteki
=> adjust graph text when consumer is 70 (per issue #118)

Gruntfile.js, README.md
Enable `livereload` in the `grunt watch` task.
- Set `livereload` to `true` in the Gruntfile
- Watch more files
- Update the readme to reflect the changes
- To test, you'll need to install the [LiveReload browser extension](http://livereload.com/extensions/) for your browser of choice. Once that's installed, run `grunt watch`, then turn on the LiveReload extension in your browser. Now, edit any of the new JS source files, any HTML template, or anything in the static directory and your browser should automagically reload the page. No more manual reloading!
- These changes should have no impact in browsers that don't have a LiveReload extension installed.
- @mistergone
- @marteki or @higs4281, can one of you test this out, too?
- I'm totally OK if we decide this isn't worth merging. It's …
=> Live reload!

retirement_api/static/retirement/css/claiming.css, retirement_api/templates/claiming.html, src/claiming-graph.js
After the "Get Estimates" button is pressed, a spinning icon should appear to indicate to the user that data retrieval is occurring, and that the button click/tap was successful. It assures the user that the tool is working, and softens the uncertainty that might come from an unusually long wait time for results.
* A `span` with an "api-data-loading-indicator" ID to the HTML file
* CSS code to hide the indicator by default, as well as to make the indicator spin
* Code in the JS to display the indicator when data retrieval begins, and hide it when it completes (or an error is received).
- Tested in Mac Chrome and Android Chrome Beta 45.0.2454.21 with no issues.
- Tested in Safari 8.0.6. **The icon appeared and disappeared as expected, but spinning didn't occur despite `-webkit-` prefixes …
=> Add a loading indicator to improve the experience for long data retrieval times

retirement_api/templates/claiming.html
Disable autocapitalize, autocomplete, autocorrect, and spellcheck for DOB and salary inputs. This change is mostly to prevent cases where autocompleting any of the fields prevents the "Get your estimate" button from becoming active.
- Add `autocapitalize`, `autocomplete`, `autocorrect`, and `spellcheck` attributes to the DOB and salary inputs
- Tested in Chrome, Safari, and my iPhone 6. The only way to enter data into the DOB and salary fields is now to type with whatever keyboard your device is using (well, other than copying and pasting, but I'm not even going there). That's important because the form is listening to `keyup` events to see if all the fields are completed and the "Get your estimate" button can be turned on; autocompleting a field doesn't fire a `keyup`.
- Can someone with …
=> Disable autocomplete for DOB and salary inputs

src/claiming-graph.js
Fix the alignment of tooltips to work with the new page paddings
- Add `pagePadding` variable to `toolTipper()`
- Tooltips near edges of screens now use `pagePadding` instead of a hard-coded number
- Tooltips at the very edge of the screen should line up (i.e. no longer look like the screenshot in https://github.com/cfpb/retirement/pull/95#issuecomment-131238422)
- Tested and working on Chrome, Safari, Chrome's device emulator, and my iPhone 6
- @marteki
- @mistergone
=> Fix tooltip padding at edges of screen

retirement_api/static/retirement/jsi18n/es/djangojs.js, src/claiming-graph.js
cases where full retirement age took the form "66 and 6 months" required a little extra gettext yoga.
- adding translations for the full retirement age value
- claiming-graph.js and the translator djangojs
- @mistergone 
- @marteki
=> translation tweak to handle birth years 1955-1959

retirement_api/utils/ss_calculator.py
Fixes errant display of benefits for age 62 when the user's birth date is 1/2/1952. At that age, the user is currently 63, so the graph should not show a value for the column representing age 62.
- extra interpolator clause to handle this case 
- enter 1/2/1952 and a salary value and check that no column appears for age 62 in the graph.
=> edge-case hot fix for birth date of 1/2/1952

package.json, src/claiming-graph.js, test/tests.js
This update corrects a bug whereby users could select (either via slider or via clicking the age number) an age younder than their current age.
**Review:**
- @ascott1
- @mistergone
- @higs4281
Includes a test to hopefully prevent future breakage.
_**Please do not deploy to production.**_ Only for testing on our dev server at the moment.
=> Fix prevention of selecting age younger than current

retirement_api/utils/ss_calculator.py, retirement_api/utils/ss_utilities.py, retirement_api/utils/tests/test_ss_utilities.py
Also lets the 'too-young' error message handle all too-young cases, even birth dates in the future.
Continuation of edge-case fixes.
- adjustments to ss_calculator and ss_utilities 
- for dob 8/20/1959 and $40000 earnings, claiming at age 65 should reduce benefits by 12%
- entering any valid date of [tomorrow's month]/[tomorrow's day]/1994 or higher, even into the future, will return the same "cannot provide an estimate if you are under 22" error message.
=> fix handling of decreases for some pre-FRA ages

.gitattributes, CHANGELOG.md, src/claiming-graph.js
This PR is a quick fix for the following bug:
> The phrase “compared to claiming at age 68” is showing up instead of "compared to claiming at FRA." This seems to happen only you reuse the calculator, use the graph to see benefit at age 68, not refresh, and the first example that you use is for someone past FRA and then resubmit with another date.
The fix does not accommodate Spanish translations. I marked that in the TODOs on this PR as a future change.
This PR also adds a `.gitattributes` file, to hopefully eliminate merge conflicts due to changelog edits.
- Add additional phrase changes for `.compared-to-full` in the JS code
- Add `.gitattributes` file that switches to `merge=union` for CHANGELOG.md
Let's compare between production and this PR. :smile: 
**Production:**
1. Load up the …
=> Fix claiming phrase error, and avoid changelog merge conflicts

CHANGELOG.md, retirement_api/utils/ss_calculator.py, retirement_api/utils/ss_utilities.py, retirement_api/utils/tests/test_ss_utilities.py
This takes care of the trickiest edge case, those born on the 1st of a month
- More utils tests 
- Pares down and renames variables
- Adjusts ss_calculator utilities, mainly `set_up_runvars` 
- Fixes wording of over-70 error messge
Here's how Hector's test cases should appear:  
- Formerly our site showed benefit at age 67 of **$1,485** (The value for being born in April 1970)
- SSA treats this combination as being born in March 1970 and returns a benefit of **$1,476** at age 67
- The new branch should show **$1,476**
- The new branch's API call `/retirement/retirement-api/estimator/4-1-1970/40000/` should show 'retiremonth' parameter of 3  
- Formerly our site showed benefit **$1,422 at age 68**, the value for being born in April 1947.
- SSA treats this combination as being born in March …
=> fix born-on-the-1st edge-case handling

gulp/tasks/browserSync.js
Just a little developer quality of life fix to make BrowserSync show the right page when `gulp watch` is run
- `startPath` to `browserSync` gulp task
Running `gulp watch` should open a new browser tab with `http://localhost:3000/before-you-claim/` loaded in it (previously `gulp watch` opened a tab with `http://localhost:3000`, which doesn't resolve to anything in standalone right now).
- @mistergone or @marteki
=> Add startPath to browserSync task

CHANGELOG.md, retirement_api/templates/base.html, retirement_api/templates/standalone_base.html, src/css/claiming.less, src/js/views/graph-view.js
This fixes phrasing on both the English and Spanish sites around the comparison to claiming at your full retirement age. It also ensures that the loading spinner points in and spins the correct direction, and removes some references to our former graphing library.
- Fix phrasing about claiming at a user's full retirement age. The undefined values should be gone!
- Removal of `raphael-min.js` calls from the base templates.
Pull down the `claiming-phrasing` branch, and run `frontendbuild.sh`. Load the site.
If a person hasn't reached their full retirement age yet, the helper text explaining how their selected age compares to their full retirement age should say:
* English: "Compared to claiming at your full benefit claiming age."
* Español: "en comparación con su plena edad de jubilación." …
=> Fix phrasing for "compared to claiming at", plus misc bug fixes

retirement_api/templates/about-es.html, retirement_api/templates/about.html, retirement_api/views.py
This shouldn't affect the about page. It just prepares for eventual delivery of Spanish content.
- load `i18n` tag
- adds language handling in the view
- about-es template. we can use the same template, as with claiming.html
- the 'about' page should be unchanged. 
- @niqjohnson @marteki @mistergone
=> drop about-es template, set up about template and view for Spanish

src/js/utils/handle-string-input.js, src/js/views/graph-view.js, test/utils.js
Decimal places in salary are being handled very poorly (they're simply removed, rather than rounded). This PR fixes that by rounded them (before being sent to the API).
- `handle-string-input.js`, which may look familiar to fans of our previous albums
- Unit tests for `handle-string-input.js`
- Some old commented-out code in the unit testing file.
- Changed front-end to rely on `handle-string-input.js` utility instead of a too-simplistic REGEX replace.
- Pull down, `gulp` and check it out.
- @marteki and @niqjohnson and @higs4281
=> Fix for decimal points in salary

src/js/views/graph-view.js
Fixes the `.benefit-modification-text` content for users between 62 and their full retirement age (see GHE/Retirement/bugs-and-issues/issues/187 for details)
- `.benefit-modification-text` no longer reads "Age XX is your full benefit claiming age." for users between 62 and FRA who've selected the lowest bar in their graph.
In the `low-bar-fix` branch, enter a birthdate that corresponds to an age between 62 and 66. Select the lowest bar on the graph. You should see a message like "Age XX reduces your monthly benefit by YY%" instead of "Age XX is your full benefit claiming age."
This fix should not change any other cases (users younger than 62, users past their full retirement page but younger than 70, users older than 70, etc.)
- @mistergone: Does that look like the right extra condition? …
=> Fix lowest bar message for users beween 62 and FRA

CHANGELOG.md, retirement_api/tests/test_views.py, retirement_api/urls.py
Give the retirement 'about' page a more specific reference name.  
This should keep eregs pages from calling the retirement about page.
- Makes the namespace 'retirement_about'
- Changes tests to match 
- Simplest to test this on build.
- @willbarton @niqjohnson @marteki @mistergone
=> improve namespace of 'about' url

CHANGELOG.md, src/css/claiming.less
This corrects the issue found in https://github.com/cfpb/retirement/issues/161. We were still explicitly defining `cf-icon` style rules even though we're now using Capital Framework, and it was conflicting with styles in the global footer.
Thanks for drawing our attention to the problem, @KimberlyMunoz!
- Lines of CSS code for `cf-icon` in the Retirement-only CSS
- @kimberlymunoz @niqjohnson @higs4281 @mistergone
=> Address redundant CSS code

.gitignore, .npmrc, CHANGELOG.md, npm-shrinkwrap.json
I ran vax and made the recommended changes, and these are the results.  
It makes sense to lose the grunt dependencies, since we moved to gulp.
- `.npmrc` file 
- generated `npm-shrinkwrap.json` file
- dropped grunt packages from `/node_modules`
- `.gitignore` to ignore the debug log
- @mistergone @niqjohnson @marteki
=> changes recommended by vax

gulp/tasks/browserSync.js, retirement_api/templates/standalone/base_update.html
Add scripts needed to make the top nav menu work in standalone
- `header.js` and `footer.js` scripts to the `standalone/base_update` template
- gulp watch path to match the new standalone URL
Running `gulp watch` from this branch should open a new browser tab that points to `http://localhost:3000/retirement/before-you-claim/`, and the page that loads there should have a working top navigation menu.
- @higs4281: Did I add those scripts in the right place in the right template?
- @mistergone or @marteki 
[Preview this PR without the whitespace changes](?w=0)
=> Show top nav menu in standalone

CHANGELOG.md, retirement_api/utils/tests/test_ss_utilities.py
This handles some edge-case oddities when tests are run on the 2nd of a month
- @niqjohnson
=> fix tests to handle runs on 2nd of month

CHANGELOG.md, src/css/claiming.less
Fix the y-axis label's position and rotation in IE 8 and IE 9
- Y-axis CSS specific to IE 8 and IE 9
You'll need to have a way to test this branch in IE 8 and IE 9, but if you do, the y-axis on the graph should look like the screenshots below.
- @marteki and/or @mistergone and/or @higs4281 
[Preview this PR without the whitespace changes](?w=0)
Before | After
--------- | ------
Before | After
--------- | ------
- We should double-check this in Saucelabs on build to be 100% sure the fixes work
=> Fix y-axis labels in IE 8 and IE 9

retirement_api/templates/standalone/on-demand/header.html
The global eyebrow language list started showing up as a bulleted list instead of a horizontal list in standalone. Adding a few missing classes to the language list fixes that.
- Eyebrow language list markup
- A bunch of automatic whitespace removals (thanks, Sublime Text!)
The list of languages in the eyebrow should look exactly like what's on production.
- @higs4281 and/or @mistergone and/or @marteki 
[Preview this PR without the whitespace changes](?w=0)
`master` | `browlift`
-------- | ----------
=> Fix the global eyebrow language list

retirement_api/utils/check_api.py
The SSA monitoring log is stored as a CSV, and this change will prevent
stray commas from throwing off CSV formatting in some error states.
- formatting tweak for error messages 
- @amymok
=> Fix logging output for csv

retirement_api/utils/check_api.py
Stop connection error messages from introducing bad quoting
- @amymok 
This hotfix will help keep our csv log clean.
=> remove quoting from error messages to keep csv logs valid

retirement_api/utils/ssa_check.py, retirement_api/utils/tests/test_ss_update_stats.py, retirement_api/utils/tests/test_ss_utilities.py
Knowing when the ssa_check test was last recalibrated will give CEE staffers
context about results of the bimonthly check of SSA benefit values.
- Improves the ssa_check return message. 
- Tweaks two edge-case tests
- @amymok
=> Add calibration date to logging

.travis.yml, retirement_api/utils/ssa_check.py, retirement_api/utils/tests/test_ss_utilities.py
This is solely related to tests that happen to run on the 30th of a month with only 30 days.  
No app functionality is involved.
=> Tests on 30th

retirement_api/templates/base.html, retirement_api/templates/standalone/base_update.html, retirement_api/templates/standalone_base.html
As part of the transition from Google Analytics to Google Tag Manager, remove old GA code which will be replaced in GTM
- References to Google Analytics code 
- @user
=> Remove google analytics references

.travis.yml, setup.py
This was primarirly accomplished using the travis cli too:
`travis setup releases`
... And adding some code to make sure sure a wheel gets generated as part of the build process (including adding config for Node 6, bower, and gulp)
I also added 'setuptools-git-version' to setup.py, which will allow setuptools to infer the version number from the git tag
=> Allow Travis to build wheels and attach them to releases

retirement_api/templates/about.html, retirement_api/templates/base.html, retirement_api/templates/claiming.html, retirement_api/templates/standalone_base.html
Cleans up the overrides for satellite apps' social sharing images. Adds images to remaining category pages.
=> Open graph fixes

retirement_api/utils/tests/test_ss_utilities.py
This test fails with the message that `month` must be 1-12, and in December this logic provides 13. Adds year and month handling for testing in December to prevent this failure.
=> Adds a fix for testing in December

retirement_api/templates/claiming.html
The `TITLE` variable isn't being set for some reason. This PR fixes that by using the `trans function` and removing the super call.  There is no need to call super for the standalone or front/base templates. 
-- Notes
The `request.build_absolute_uri` block is currently empty, not sure why.
=> Fix for meta tag on `/retirement/before-you-claim/`

.travis.yml, retirement_api/utils/tests/test_ss_utilities.py
Currently, this test will fail every year since it depends on numbers
based on "today" being in 2017.  Instead, we can just specify the year when we define
"today".
@chosak and I paired on this.
=> Specify year in `test_get_test_params_in_january`

requirements.txt, test_settings.py
This change adds support for using the `DATABASE_URL` environment variable to specify Django's test database, based on the [dj-database-url](https://github.com/kennethreitz/dj-database-url) package.
It lets you run tests against e.g. Postgres:
```sh
$ DATABASE_URL=postgres://user@localhost/db ./pytest.sh
```
(Note that this will require first creating a local database and `pip install`ing `psycopg2==2.7.3.2`.)
It adds `dj-database-url==0.4.2` to the test requirements as that matches the current version in cfgov-refresh.
- @chosak  and I paired on this. This is part of the work being done on platform#2567 to add Postgres compatibility to all cf.gov code. We're hoping to use this pattern with all satellite apps to make database testing easier everywhere.
=> Support optional testing of other databases

CONTRIBUTING.md, retirement_api/fixtures/retiredata.json, retirement_api/locale/es/LC_MESSAGES/django.po
Some content moved on the IRS site. This corrects those links.
Testing:
- Run the setup instructions at https://github.com/cfpb/retirement#installation if you don't already have `retirement` set up
- Go to http://localhost:8000/retirement/before-you-claim/
- Verify that the links under Step 3 go to the new locations
=> Update external IRS links

test_settings.py
This cleans up a minor settings mistake for the sake of future content updates.
The standalone test_settings.py file specified a `FIXTURES_DIRS`, which isn't needed unless fixtures are in an unexpected place. This was causing the properly placed retiredata fixture to load twice, which is harmless but could worry someone updating content in the future.
As this only affects stand-alone operations, this does not need to be released or deployed. It can safely wait for the next code change that does need deployment.
=> minor cleanup of standalone settings

retirement_api/static/retirement/admin/js/admin/RelatedObjectLookups.js
`noopener` should be added to `window.open` so that the new window does not have access back to the originating window, as checkmarx flags this as a security vulnerability. (Reported by @lfatty)
See https://developer.mozilla.org/en-US/docs/Web/API/Window/open#noopener
=> Add noopener attribute to window.open

README.md, requirements.txt, retirement_api/utils/ss_calculator.py, retirement_api/utils/ss_update_stats.py, retirement_api/utils/tests/test_ss_update_stats.py
This change removes the dependency and use of the [lxml](https://lxml.de/) library for parsing the HTML retrieved from the SSA. BeautifulSoup is instructed to use Python's `html.parser` instead.
See [the BS documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-a-parser) for a quick comparison of the available parsers:
All functionality works properly, and unit tests all pass, when using this alternate parser. To test, follow the instructions in this repository's README.
You can see sample HTML output which gets parsed by this parser by running this curl command which hits the SSA quick calculator in the same way that this app does:
```sh
curl -v -d "dobmon=1&dobday=30&yob=1960&earnings=50000" https://www.ssa.gov/cgi-bin/benefit6.cgi
```
The returned HTML parses …
=> Deprecate use of lxml for html parsing

.travis.yml
Travis frontend builds run on a Linux platform, different from the Mac platform typically used for development. This can cause differences in the package-lock.json file due to the inclusion of optional modules.
See this lengthy npm thread that describes the problem:
https://github.com/npm/npm/issues/17722
To avoid this issue, this change runs `npm config set package-lock false` to disable the use of lock files when doing the npm install.
We already do something similar to this in Capital Framework:
https://github.com/cfpb/capital-framework/blob/821dd4fafb65b947ea436fd57b18a195f57e71b2/.travis.yml#L9
This change is needed because if the `package-lock.json` file is modified by the build, then the Python wheel name generated by [setuptools-git-version](https://pypi.org/project/setuptools-git- …
=> Disable package-lock.json on Travis

setup.py
This was causing a conflict when this satellite app was embedded in
cfgov-refresh because django-filter 0.9.2 isn't compatible with
djangorestframework 3.6.4 (which is necessary for cfgov-refresh as we
update to django 1.11).
We could have upgraded django-filter to a higher version, but since it
seems to be unused, we're simply removing it.
=> Remove django-filter, since it is never used

retirement_api/utils/tests/test_ss_utilities.py, setup.py
One unit test began failing recently:
[`retirement_api.utils.tests.test_ss_utilities.UtilitiesTests.test_interpolate_for_past_fra`](https://github.com/cfpb/retirement/blob/a2a9a590a0ae2ac5bf931f89129b136578cc7ae8/retirement_api/utils/tests/test_ss_utilities.py#L350)
This seems to caused by the way that some of this project's tests make use of `datetime.today` to determine the current day. This means that the tests are running using slightly different data depending on the day on which they are run. This makes it so that the edge cases of different date calculations may work one day but not the next.
To fix this particular error, this change brings in the Python [freezegun](https://github.com/spulec/freezegun) package that lets you "freeze time" when running tests. This dependency is only …
=> Fix tests that fail when run on certain days

README.md, src/css/main.less
This commit modifies the default loading strategy for our licensed font to use the Fonts.com CDN instead of looking for the file locally. This means that when building and loading this repository locally, the webfont will be loaded from the CDN. I've updated the README to indicate how this behavior may be changed if you want to load the font locally.
This is necessary because making the default local loading means that the built CSS includes references to a local `webfonts` directory that will not exist in a built Python package. This then fails Django `collectstatic` when run in a certain way.
=> Change default webfont loading to use CDN

package-lock.json, package.json, src/css/main.less
I noticed a number of capital framework packages that appear to be unused.
- Removes capital-framework packages that are unused in the project.
- Re-generates package-lock.
1. `npm test` should pass.
2. Follow https://github.com/cfpb/retirement#installation and the project should look and work the same as the live site.
=> Remove unused capital-framework

retirement_api/templates/retirement_api/claiming.html
The retirement questions suddenly stopped rendering, and we found an empty link at the spot where the page was failing. Removing the empty link restores the questions.
=> Remove empty link to fix page

.travis.yml, retirement_api/models.py, retirement_api/tests/test_commands.py, retirement_api/tests/test_views.py, retirement_api/utils/ss_update_stats.py, setup.py, tox.ini
Remove python 2 from Tox testing, Travis, and setup.py.
Remove the `six` library.
1. `tox`
=> Remove python 2 compatibility

retirement_api/views.py
Resolves a bug around the mega menu presenting as its english version on the spanish claiming page.
- Provides the language key into the claiming view.
1. [Claiming Page in Spanish](http://localhost:8000/consumer-tools/retirement/before-you-claim/es/)
=> Include the language key for the mega menu

README.md, retirement_api/templates/retirement_api/about.html, retirement_api/templates/retirement_api/claiming.html, retirement_api/templates/retirement_api/standalone/base_update.html, setup.py, tox.ini
This change updates our supported version range to the LTS release of Django (2.2) and the current release of Django (3.1).
Removed support for Django 1.11
- Added support for Django 3.1
- {% load staticfiles %} and {% load admin_static %} were deprecated in Django 2.1, and removed in Django 3.0
1. tox
=> Support LTS + Current versions of Django

README.md
Replace Travis Badge with Github Action Badge
- Replace Travis Badge with Github Action Badge
=> Replace Travis Badge with Github Action Badge

retirement_api/views.py
Currently the Spanish version of the "About this tool" page shows the English mega-menu; it should show the Spanish mega-menu. (See GHE/CFGOV/platform/issues/3912 for more details.)
The about page just needed the same fix as we made in https://github.com/cfpb/retirement/pull/259
- `language` key to the about page
1. Install this version of the retirement app in cf.gov using the [method of your choice](https://cfpb.github.io/consumerfinance.gov/related-projects/#developing-python-packages-with-consumerfinancegov)
2. Go to /consumer-tools/retirement/before-you-claim/about/es/ and make sure the Spanish version of the mega-menu appears (and that all the other Spanish content continues to appear)
3. Go to /consumer-tools/retirement/before-you-claim/about/ and make sure the English version of …
=> Show the Spanish mega-menu on about page

retirement_api/views.py
In conjunction with a forthcoming PR to consumerfinance.gov, these will enable the banner on Beta and requesting the Spanish mega menu explicitly instead of relying on a default.
- Context variables `show_banner` and `show_mega_menu` on the `claiming` and `about` views
[To be filled in once related cf.gv PR is open.]
1.
-
-
=> Add show_banner and show_mega_menu context vars to views

settings/standalone.py
We've removed CSRF from non-authenticated paths in https://github.com/cfpb/consumerfinance.gov/pull/6366. The PR removes the CSRF middleware from the standalone testing settings.
=> Remove CSRF middleware in settings
