api/settings.py
api/templates/base.html
api/templates/main.html
api/urls.py
api/views.py

Dataside demo template

---

browser_testing/features/environment.py
browser_testing/features/example-environment.cfg
browser_testing/features/navigation.feature
browser_testing/features/pages/base.py
browser_testing/features/steps/steps_home.py
browser_testing/features/steps/steps_navigation.py

- Added a FAST_FAIL tag to make the test abort if the page returns a 404 error

Updated links, added handle error tags

---

retirement_api/templates/claiming.html

Dependent on tooltip content being deployed through Django admin. Also, pay no attention to the commit message that mentions "catsup contributions". :scream: 
Review requested by @mistergone @niqjohnson or @higs4281

Updating to cleared content and cleared tooltips

---

retirement_api/static/js/claiming-social-security.js

Use note field instead of error field

---

retirement_api/static/css/claiming.css
retirement_api/static/js/claiming-social-security.js
retirement_api/templates/claiming.html

Changes for notifications, fixes for full age benefits display, and changes and fixes to the lifestyle questions.

Multiple fixes!

---

retirement_api/static/css/claiming.css
retirement_api/static/js/claiming-social-security.js

This PR encompasses multiple improvements to dynamic resizing of the graph portion.
Check it out! :cyclone: :octopus:

Graph resizing, more better improvements

---

retirement_api/static/css/claiming.css
retirement_api/static/js/nemo.js
retirement_api/templates/base.html
retirement_api/templates/claiming.html
retirement_api/templates/standalone_base.html

Included:
* Responsive header and navigation
* Responsive footer
The toggle-menu Javascript doesn't work properly yet, but as @higs4281 pointed out, we don't need it for this release (i.e. for usability testing).

Responsive header and footer!

---

retirement_api/static/css/claiming.css
retirement_api/static/js/claiming-social-security.js

This PR should contain fixes for all screen sizes.

Fixes responsive styles

---

retirement_api/static/retirement/js/claiming-social-security.js

Fix for IE

---

retirement_api/static/retirement/css/claiming.css

* Shift the y-axis 7 pixels left on smaller screens
* Move the "Age XX is..." text up to better align with the top of the graph SVG.

Small spacing tweaks

---

retirement_api/fixtures/retiredata.json
retirement_api/utils/ss_utilities.py

add myRA italics in the too-old error message and trim explainer graf (issue 98)

---

Gruntfile.js
package.json
retirement_api/static/retirement/js/claiming-social-security.js
retirement_api/templates/base.html
retirement_api/templates/standalone_base.html
src/claiming-functions.js
src/claiming-graph.js

This PR is an introduction of grunt into our code. It starts with a very simple concatenation, which I'll build on in the future. This will make it easy to add automated testing into our front-end build.
I'll explain how this affects front-end development at our next stand-up, for anyone who's curious. :microscope: :octopus:

Basic grunt task preparation

---

CHANGELOG.md
Gruntfile.js
conf/eslint.yaml
package.json

Added [linting](https://en.wikipedia.org/wiki/Lint_%28software%29) to grunt tasks and added `gruntify-eslint` to our npm packages.
- added `gruntify-eslint` to `package.json`
- added `grunt lint` task that runs lint task
- added a `conf` directory for configurations, and added `eslint.yaml` (which is a slight edit of our front-end standards `.eslintrc` file)
- @marteki, @higs4281, @niqjohnson - pull this in and try it, please, and try not to be horrified by the results of the linting. :grin:

Add linting to grunt tasks

---

frontendbuild.sh
setup.py

Add frontend script for deployments
- shell build script
- @mistergone

add build script for front end

---

CHANGELOG.md
retirement_api/utils/ss_calculator.py

- timeout value bumped up to avoid caching of occasional slow SSA response
- improves docstring and variable comments, per SAG recommendations
- @mistergone 
- @willbarton

adjust timeout value, address SAG recommendations

---

retirement_api/utils/ss_calculator.py
retirement_api/utils/ss_utilities.py
retirement_api/utils/tests/test_ss_utilities.py
retirement_api/views.py

Refactors calculator and fixes two bugs
- calculator functions for parsing and var setup
- code to handle monthwise reductions properly for under-FRA users
- fixed error message that falsely reported low earnings entered 
- for birth date 2/1/1951, the reduction at age 64 should be 7 or 8 percent, not 13.
- @marcesher

Calculator

---

retirement_api/utils/ss_calculator.py
retirement_api/utils/tests/test_ss_utilities.py

Makes edge-case tweak for testing.
for dob 1/2/1959, reduction at age 62 should be 29-30%

hotfix tweak for testing

---

retirement_api/static/retirement/css/main.css

As observed by @nataliafitzgerald.
Am I correct in ascertaining that this project doesn't build its CSS from Less?
**Review, please:**
- @niqjohnson

Fix button text size

---

retirement_api/utils/tests/test_ss_utilities.py
src/claiming-graph.js

This PR fixes the lifetime benefits number when the user's age is greater than 62.
- Code to fix lifetime benefits
- @marteki @higs4281 @niqjohnson

Fix for lifetime benefits

---

gulp/config.js
retirement_api/utils/tests/test_ss_utilities.py
src/js/claiming-graph.js
src/js/index.js
src/js/models/benefits-model.js
src/js/utils/nemo.js
src/js/views/graph-view.js
src/js/views/questions-view.js
src/js/views/tooltips-view.js
src/js/wizards/fetch-api-data.js
src/js/wizards/get-model-values.js
src/js/wizards/update-model.js

This PR moves the code into a MV* framework I'm calling "Model-View-Wizard"! Wizards have got it going on.
- Several files (which just have code that used to be in two big files)
- Moved code into a bunch of smaller files.
- Unit tests changes to use new files
- Pull down, run `frontendbuild.sh`, and make sure everything works!
- @marteki and @niqjohnson and @higs4281 
- The graph view is still big and messy, so refactoring it on my To Do List.
Thanks to @marteki and @niqjohnson for their patience while I rework all this stuff. Thanks to @ascott1 for help setting up `college-costs`, which became a template for this project!

Model-View-Wizard!

---

CHANGELOG.md
retirement_api/management/commands/check_ssa.py
retirement_api/management/commands/check_ssa_values.py
retirement_api/tests/test_commands.py
retirement_api/utils/check_api.py
retirement_api/utils/tests/test_api_check.py

This allows Jenkins to run a regular functional test against SSA's Quick
Calculator to be sure it's working, log the results and warn of failures.
- New management command `check_ssa` and related test  
This joins the `check_ssa_values` command for monitoring SSA benefit values
-  `./pytest.sh` should run without errors
- you could also give `./manage.py check_ssa` a spin
- @amymok

Adds a manage.py command to test SSA via our API

---

.coveragerc
.gitignore
CHANGELOG.md
retirement_api/tests/test_models.py
retirement_api/utils/ss_calculator.py
retirement_api/utils/ss_utilities.py
retirement_api/utils/tests/test_ss_utilities.py
retirement_api/views.py
setup.py

This removes old code that was causing an error noted in #194 .
It also adds a backup validation test to bail early if a bad date slips through.

Catch bad dates

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

Regenerate shrinkwrap file to remove optional dependencies

Regenerate shrinkwrap file to remove optional dependencies

---

setup.py

Bumping version in setup.py

---

retirement_api/templates/claiming.html

Add's the search description requested in GHE platform issue 1095

add search description

---

retirement_api/templates/claiming.html

Adds page title to FB preview

---

retirement_api/templates/base.html
retirement_api/templates/standalone/base_update.html
retirement_api/templates/standalone_base.html

Changes sharing image to retirement-specific category image.

Search description

---

CONTRIBUTING.md

As part of https://github.com/cfpb/development/issues/134 this PR aims to document the current level of browser support within this project.

Documenting browser support

---

CHANGELOG.md
package-lock.json
package.json

- Fixes incorrect release version in package.json.
- Updates license field in package.json to reference TERMS.md.
- Updates `ansi-colors`, `gulp-rename`, `protractor`, `snyk`, `webpack`, and `webpack-stream`.
- Follow installation https://github.com/cfpb/retirement#installation
- `npm test` should pass.

Updates dependencies and package.json meta data

---

README.md
browser_testing/features/steps/decorators.py
manage.py
pytest.sh
retirement_api/management/commands/check_ssa.py
retirement_api/management/commands/check_ssa_values.py
retirement_api/tests/test_commands.py
retirement_api/utils/check_api.py
retirement_api/utils/ss_update_stats.py
retirement_api/utils/ss_utilities.py
retirement_api/utils/ssa_check.py
retirement_api/utils/tests/test_ss_update_stats.py
settings/standalone.py
settings/test.py
setup.py
test_settings.py
tox.ini

- Update required python libraries to have flexible versions, and ensure the versions are in line with what is required by cfgov-refresh.
- Remove all console output from tests
- Fix many linter errors, especially unused imports and variables
- Update `except` clauses to only catch specific exceptions ([read more here](https://docs.python.org/2/howto/doanddont.html#except))
- Use "standalone" settings for running the server. Use "test" settings when running `tox`. This allows us to silence unnecessary logged output during test runs

Update Libraries and Fix Linter Errors

---

src/js/views/graph-view.js
src/js/views/next-steps-view.js
src/js/views/questions-view.js
src/js/views/tooltips-view.js

- Bugfix: correctly imports `isElementInView` instead of `require`.
- Unnests JavaScript view files and only exports public functions.
- Removes unused `mouseCoords`, `indicator`, `sliderLine`, `graphBackground`, and `bars` variables from graph-view.
1. Follow project installation instructions, open dev console, and test project for errors in console.

Refactor JS to unnest view objects
